# Generated by Django 3.0.6 on 2020-05-28 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Промо заголовок')),
                ('content_title', models.CharField(max_length=100)),
                ('content_text', models.CharField(max_length=3000)),
                ('footer_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PromoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=300)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Promo')),
            ],
        ),
    ]
